//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public System.DateTime ValidThru { get; set; }
        public int CVC { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
